---
abstract: 'Query and install CPAN modules realtime from the fresh mirror'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CPAN-Fresh
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  App::Cmd: 0.30
  CPAN::Inject: 0
  Filter::Util::Call: 0
  JSON: 2.0
  LWP: 0
  Time::Piece: 0
  URI: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/cpanf.git
version: 0.11
